<a href="https://colab.research.google.com/github/patero22/PyTorch_Course/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00 PyTorch Fundamentals
resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

Questions on github/discussions

In [1]:
print("Pytorch")

Pytorch


In [2]:
!/usr/local/cuda/bin/nvcc --version


nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Tue_Aug_15_22:02:13_PDT_2023
Cuda compilation tools, release 12.2, V12.2.140
Build cuda_12.2.r12.2/compiler.33191640_0


In [3]:
!nvidia-smi #zmienione w runtime type na t4 gpu

/bin/bash: line 1: nvidia-smi: command not found


In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import torch
print(torch.__version__)


2.3.0+cu121


## Introduction to tensors
Creating tensors

PyTorch tensor are created using 'troch.Tensor()' -= https://pytorch.org/docs/stable/tensors.html

In [5]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [7]:
# Get tensor back as Python int
scalar.item()

7

In [8]:
#Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [11]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                        [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [12]:
MATRIX.ndim

2

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])

TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [18]:
TENSOR2= torch.tensor([[[1],[2],[3],[4],[5],[6]]])

TENSOR2

tensor([[[1],
         [2],
         [3],
         [4],
         [5],
         [6]]])

In [19]:
TENSOR2.ndim

3

In [20]:
TENSOR2.shape

torch.Size([1, 6, 1])

In [21]:
TENSOR3= torch.tensor([[[1],[2]],[[3],[4]],[[5],[6]]])

TENSOR3

tensor([[[1],
         [2]],

        [[3],
         [4]],

        [[5],
         [6]]])

In [22]:
TENSOR3.ndim

3

In [23]:
TENSOR3.shape

torch.Size([3, 2, 1])

### RANDOM TENSORS

Random tensor are imprtant because the way many neural netowrks learn is that they start with tensors full of random numbers and then adjuct thise random numbers to better represent the data

Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers

torch.rand = https://pytorch.org/docs/stable/generated/torch.rand.html

In [24]:
#Random tensors
#Create random tensor of shape/shape (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.5319, 0.2118, 0.7730, 0.9823],
        [0.3477, 0.1230, 0.2227, 0.1772],
        [0.6574, 0.8733, 0.7378, 0.9847]])

In [25]:
#Create a random tensor with similar shape to an image
random_image_size_tensor = torch.rand(size=(224,224,3)) #height,width,colour channels (R,G,B)
random_image_size_tensor

tensor([[[0.6999, 0.3668, 0.0412],
         [0.3599, 0.0738, 0.7065],
         [0.8871, 0.8869, 0.6570],
         ...,
         [0.5315, 0.8018, 0.2053],
         [0.7842, 0.7472, 0.9170],
         [0.3148, 0.1700, 0.7334]],

        [[0.3905, 0.4062, 0.7491],
         [0.7177, 0.3626, 0.2907],
         [0.7664, 0.1342, 0.7192],
         ...,
         [0.5274, 0.6320, 0.1289],
         [0.9129, 0.8641, 0.0528],
         [0.2082, 0.6256, 0.4372]],

        [[0.7979, 0.8777, 0.7853],
         [0.2966, 0.6425, 0.6058],
         [0.2959, 0.2330, 0.2249],
         ...,
         [0.4820, 0.0673, 0.2139],
         [0.1391, 0.0454, 0.2736],
         [0.3299, 0.8235, 0.6956]],

        ...,

        [[0.1903, 0.6836, 0.4794],
         [0.3871, 0.7834, 0.6584],
         [0.7867, 0.2672, 0.8936],
         ...,
         [0.2268, 0.2128, 0.0157],
         [0.7498, 0.6013, 0.6716],
         [0.8669, 0.9895, 0.4685]],

        [[0.8762, 0.5162, 0.9394],
         [0.9826, 0.6955, 0.0620],
         [0.

### Zeros and ones

In [26]:
# Create a tensor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [27]:
# tensor of all ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [28]:
ones.dtype

torch.float32

### Create a range of tensors and tensors-like

In [29]:
# use torch.arange()

one_to_ten = torch.arange(start=0,end=1000, step=77)
one_to_ten

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [30]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [31]:
#Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False) #track gradiens with this tensor operations
float_32_tensor

tensor([3., 6., 9.])

In [32]:
float_32_tensor.dtype

torch.float32

In [33]:
float_16_tensor = float_32_tensor.type(torch.half) #torch.half = torch.float16
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [34]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [35]:
int_32_tensor = torch.tensor([3,6,9],dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [36]:
float_32_tensor*int_32_tensor

tensor([ 9., 36., 81.])

### Getting infromation from tensors

tensor.dtype
tensor.shape
tensor.device

In [37]:
#some tensor
some_tensor = torch.rand(3,4)

In [38]:
print(some_tensor)

tensor([[0.6455, 0.0409, 0.6791, 0.0897],
        [0.6875, 0.1455, 0.2235, 0.6697],
        [0.4344, 0.9488, 0.6185, 0.6909]])


In [39]:
print(some_tensor.dtype)

torch.float32


In [40]:
print(some_tensor.shape)

torch.Size([3, 4])


In [41]:
print(some_tensor.device)

cpu


### Manipulating tensor (tensor operations)

operations include:
* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix multplication

In [42]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [43]:
tensor * 10

tensor([10, 20, 30])

In [44]:
#Try out PyTorch inbuilt fucntions
torch.mul(tensor,10)

tensor([10, 20, 30])

### MATRIX Multiplication (dot product)

In [45]:
#Matrix multiplication
torch.matmul(tensor,tensor) #much faster than loop version

tensor(14)

In [46]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 794 µs, sys: 772 µs, total: 1.57 ms
Wall time: 2.26 ms


### One of the most common errors in deep leraning is shape error (in matrix multiplication for example)

#### Transposition of tensor

In [47]:
tensor.T

<ipython-input-47-658225b2fec8>:1: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3675.)
  tensor.T


tensor([1, 2, 3])

## Finding the min,max,mean,sum,etc (tensor aggregation)

In [48]:
#Create a tensor
x = torch.arange(1,100,10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [49]:
torch.min(x), x.min()

(tensor(1), tensor(1))

In [50]:
torch.max(x)

tensor(91)

torch.mean(x)

In [52]:
torch.mean(x.type(torch.float32))

tensor(46.)

x.mean()

In [55]:
x.type(torch.float32).mean()

tensor(46.)

In [57]:
torch.sum(x),x.sum()

(tensor(460), tensor(460))

### Findinf the positional min and max

In [58]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [59]:
x.argmin()

tensor(0)

In [60]:
x.argmax()

tensor(9)

## Reshaping, stacking , squeezing and unsqueezing tensors
* Reshaping - reshape a input tensor to a defined shape
* View - Return a view of an input tensor of certain shaoe but keep the same memoryview
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removs all '1' dimensions from a tensor
* Unsqueeze - add a '1' dimension to a target tensor
* Permute - return a view of the input with dimensions permuted (swapped) i a certain way

In [61]:
#Creae a tensor
import torch
x= torch.arange(1.,10.0)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [62]:
# add an extra dimension

x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [63]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [64]:
# Changing z changes x (because a view of a tensor shares the same memory of the original input)
z[:, 0]=5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [65]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x])

In [66]:
print(x_stacked)

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])


In [67]:
#troch.squeeze()
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [68]:
x_reshaped.shape

torch.Size([1, 9])

In [69]:
x_squeezed=x_reshaped.squeeze()

In [70]:
x_reshaped.squeeze().shape

torch.Size([9])

In [71]:
#torch.unsqueeze() - adds a single dimensins to a tensor at specific dim
print(f"Previous target : {x_squeezed}")
print(f"Previous shape : {x_squeezed.shape}")
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"New target : {x_unsqueezed}")
print(f"New shape : {x_unsqueezed.shape}")

Previous target : tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape : torch.Size([9])
New target : tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape : torch.Size([1, 9])


In [72]:
# torch.permute - rearange the dimensions of a tensor in a specific order
x_original = torch.rand(size=(224,224,3)) #height,width,colour

# Permute the original tensor to rearrange the axis (dim ) order

x_permuted = x_original.permute(2, 0, 1) #now its size=(3, 224, 224)

x_original.shape , x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

## Indexing

In PyTorch the same as in NumPy

In [73]:
# Create a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [74]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [75]:
x[0][0] , x[0,0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [76]:
x[0][0][0] , x[0,0,0]

(tensor(1), tensor(1))

In [77]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [78]:
# all from 0 dim but only 1 index value of 1st ,a 2nd dimensions
x[:,1,1]

tensor([5])

In [79]:
x[0,2,2]

tensor(9)

In [80]:
x[0,:,2]

tensor([3, 6, 9])

## PyTorch tensors and NumPy

* Data in NumPy, want in PyTorch tensor -> torch.from_numpy(ndaarray)
* PyTorch tensor -> NumPy   -    torch.Tensor.numpy()

In [81]:
# NumPy array to tensor
import torch, numpy as np

In [82]:
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array) # warning pytorch reflet dtype from numpy so tensor will have float64 not float32 like default
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [83]:
# Change the value of array, what will this do to 'tensor' ?
array += 1
array , tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([2., 3., 4., 5., 6., 7., 8.], dtype=torch.float64))

In [84]:
array1 = np.arange(1.0,8.0)
tensor1 = torch.from_numpy(array1) # warning pytorch reflet dtype from numpy so tensor will have float64 not float32 like default
array1, tensor1



(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [85]:
# Change the value of array, what will this do to 'tensor' ?
array1 = array1 + 1
array1 , tensor1

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [86]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [87]:
tensor.dtype , numpy_tensor.dtype #so it's copying data type

(torch.float32, dtype('float32'))

In [88]:
#Change the tensor, what happends to ,numpy_tensor' ?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random nubers to try and make them better representatuins of data -> again .. `

To reduce the rnadomness in neural networks and PyTorch comes the ceoncept of a **random seed**

Essentially what the random seed does is "flavour" the randomness.

In [91]:
# Create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

random_tensor_A, random_tensor_B , random_tensor_A == random_tensor_B

(tensor([[0.9458, 0.2039, 0.2287, 0.4704],
         [0.2026, 0.5616, 0.7755, 0.5739],
         [0.9858, 0.8514, 0.4718, 0.3087]]),
 tensor([[0.4467, 0.4235, 0.6991, 0.8967],
         [0.7489, 0.8151, 0.6958, 0.6897],
         [0.5571, 0.0820, 0.8609, 0.7306]]),
 tensor([[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]))

In [107]:
# Let's make some random but reporducible tensors

#Set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C, random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]]) tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs (and making faster computations)



### 1. Getting a GPU

1. Use Google
2. Use your own GPU
3. Cloud computing

In [1]:
!nvidia-smi

Wed Jul  3 13:59:38 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   42C    P8              10W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

### 2.Check for GPU access with PyTorch

In [2]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

### Important link:
https://pytorch.org/docs/stable/notes/cuda.html#best-practices

In [3]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [4]:
# Count number of devices
torch.cuda.device_count()

1

### 3. Putting tensors (and moedels) on the GPU

The reason we want out tensors/models on the GPU is beacuse using GPU results in faster computations

In [6]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1,2,3], device = "cpu")

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [7]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu


tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to teh CPU

 If tensor is on GPU, can't transform it to numpy
tensor_on_gpu.numpy()

In [9]:
# To fix the GPU tensor with NumPy issue, we can forst set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [10]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')