<a href="https://colab.research.google.com/github/patero22/PyTorch_Course/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00 PyTorch Fundamentals
resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

Questions on github/discussions

In [2]:
print("Pytorch")

Pytorch


In [3]:
!/usr/local/cuda/bin/nvcc --version


nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Tue_Aug_15_22:02:13_PDT_2023
Cuda compilation tools, release 12.2, V12.2.140
Build cuda_12.2.r12.2/compiler.33191640_0


In [4]:
!nvidia-smi #zmienione w runtime type na t4 gpu

/bin/bash: line 1: nvidia-smi: command not found


In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import torch
print(torch.__version__)


2.3.0+cu121


## Introduction to tensors
Creating tensors

PyTorch tensor are created using 'troch.Tensor()' -= https://pytorch.org/docs/stable/tensors.html

In [6]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [7]:
scalar.ndim

0

In [8]:
# Get tensor back as Python int
scalar.item()

7

In [9]:
#Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [10]:
vector.ndim

1

In [11]:
vector.shape

torch.Size([2])

In [12]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                        [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [13]:
MATRIX.ndim

2

In [14]:
MATRIX.shape

torch.Size([2, 2])

In [15]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])

TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [16]:
TENSOR.ndim

3

In [17]:
TENSOR.shape

torch.Size([1, 3, 3])

In [18]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [19]:
TENSOR2= torch.tensor([[[1],[2],[3],[4],[5],[6]]])

TENSOR2

tensor([[[1],
         [2],
         [3],
         [4],
         [5],
         [6]]])

In [20]:
TENSOR2.ndim

3

In [21]:
TENSOR2.shape

torch.Size([1, 6, 1])

In [22]:
TENSOR3= torch.tensor([[[1],[2]],[[3],[4]],[[5],[6]]])

TENSOR3

tensor([[[1],
         [2]],

        [[3],
         [4]],

        [[5],
         [6]]])

In [23]:
TENSOR3.ndim

3

In [24]:
TENSOR3.shape

torch.Size([3, 2, 1])

### RANDOM TENSORS

Random tensor are imprtant because the way many neural netowrks learn is that they start with tensors full of random numbers and then adjuct thise random numbers to better represent the data

Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers

torch.rand = https://pytorch.org/docs/stable/generated/torch.rand.html

In [25]:
#Random tensors
#Create random tensor of shape/shape (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.8212, 0.8248, 0.5248, 0.4491],
        [0.2154, 0.1313, 0.0135, 0.4542],
        [0.1696, 0.9821, 0.6565, 0.4293]])

In [26]:
#Create a random tensor with similar shape to an image
random_image_size_tensor = torch.rand(size=(224,224,3)) #height,width,colour channels (R,G,B)
random_image_size_tensor

tensor([[[9.1465e-01, 6.3008e-01, 4.3206e-01],
         [8.4657e-01, 3.9154e-01, 8.1637e-01],
         [6.1487e-01, 9.0627e-01, 1.3681e-01],
         ...,
         [3.4051e-01, 6.6781e-01, 6.4490e-02],
         [8.3311e-01, 6.3731e-01, 1.4474e-01],
         [7.6584e-01, 4.8654e-01, 7.1919e-01]],

        [[7.9491e-01, 7.9985e-01, 9.3955e-01],
         [2.3250e-01, 8.1577e-01, 5.2083e-01],
         [1.9905e-01, 3.9100e-01, 2.3738e-01],
         ...,
         [5.7524e-01, 5.4342e-01, 4.7200e-01],
         [6.2568e-01, 2.5152e-01, 1.8723e-01],
         [9.0449e-01, 7.3187e-01, 6.8122e-01]],

        [[1.3637e-01, 7.9001e-02, 7.5213e-01],
         [8.3949e-01, 5.5349e-01, 8.4124e-01],
         [3.4202e-01, 4.3685e-01, 1.7709e-01],
         ...,
         [8.0632e-01, 2.6162e-01, 1.5293e-01],
         [3.9610e-01, 2.9575e-01, 1.3351e-01],
         [8.3663e-01, 6.3204e-01, 4.2561e-01]],

        ...,

        [[4.5612e-01, 3.4110e-01, 5.7793e-02],
         [6.7395e-02, 4.4363e-02, 9.4937e-01]

### Zeros and ones

In [27]:
# Create a tensor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [28]:
# tensor of all ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [29]:
ones.dtype

torch.float32

### Create a range of tensors and tensors-like

In [30]:
# use torch.arange()

one_to_ten = torch.arange(start=0,end=1000, step=77)
one_to_ten

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [31]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [32]:
#Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False) #track gradiens with this tensor operations
float_32_tensor

tensor([3., 6., 9.])

In [33]:
float_32_tensor.dtype

torch.float32

In [34]:
float_16_tensor = float_32_tensor.type(torch.half) #torch.half = torch.float16
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [35]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [36]:
int_32_tensor = torch.tensor([3,6,9],dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [37]:
float_32_tensor*int_32_tensor

tensor([ 9., 36., 81.])

### Getting infromation from tensors

tensor.dtype
tensor.shape
tensor.device

In [38]:
#some tensor
some_tensor = torch.rand(3,4)

In [39]:
print(some_tensor)

tensor([[0.0795, 0.9159, 0.6671, 0.5289],
        [0.0835, 0.6047, 0.2238, 0.5230],
        [0.1083, 0.1250, 0.5088, 0.2893]])


In [40]:
print(some_tensor.dtype)

torch.float32


In [41]:
print(some_tensor.shape)

torch.Size([3, 4])


In [42]:
print(some_tensor.device)

cpu


### Manipulating tensor (tensor operations)

operations include:
* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix multplication

In [43]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [44]:
tensor * 10

tensor([10, 20, 30])

In [45]:
#Try out PyTorch inbuilt fucntions
torch.mul(tensor,10)

tensor([10, 20, 30])

### MATRIX Multiplication (dot product)

In [49]:
#Matrix multiplication
torch.matmul(tensor,tensor) #much faster than loop version

tensor(14)

In [48]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 2.21 ms, sys: 755 µs, total: 2.96 ms
Wall time: 5.69 ms


### One of the most common errors in deep leraning is shape error (in matrix multiplication for example)

#### Transposition of tensor

In [50]:
tensor.T

<ipython-input-50-658225b2fec8>:1: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3675.)
  tensor.T


tensor([1, 2, 3])

## Finding the min,max,mean,sum,etc (tensor aggregation)

In [52]:
#Create a tensor
x = torch.arange(1,100,10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [53]:
torch.min(x), x.min()

(tensor(1), tensor(1))

In [54]:
torch.max(x)

tensor(91)

In [55]:
torch.mean(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [56]:
torch.mean(x.type(torch.float32))

tensor(46.)

In [57]:
x.mean()

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [58]:
x.type(torch.float32).mean()

tensor(46.)

In [59]:
torch.sum(x),x.sum()

(tensor(460), tensor(460))

### Findinf the positional min and max

In [62]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [63]:
x.argmin()

tensor(0)

In [64]:
x.argmax()

tensor(9)

## Reshaping, stacking , squeezing and unsqueezing tensors
* Reshaping - reshape a input tensor to a defined shape
* View - Return a view of an input tensor of certain shaoe but keep the same memoryview
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removs all '1' dimensions from a tensor
* Unsqueeze - add a '1' dimension to a target tensor
* Permute - return a view of the input with dimensions permuted (swapped) i a certain way

In [67]:
#Creae a tensor
import torch
x= torch.arange(1.,10.0)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [68]:
# add an extra dimension

x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [69]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [71]:
# Changing z changes x (because a view of a tensor shares the same memory of the original input)
z[:, 0]=5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [72]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x])

In [73]:
print(x_stacked)

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])
