<a href="https://colab.research.google.com/github/patero22/PyTorch_Course/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00 PyTorch Fundamentals
resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

Questions on github/discussions

In [ ]:
print("Pytorch")

Pytorch


In [ ]:
!/usr/local/cuda/bin/nvcc --version


nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Tue_Aug_15_22:02:13_PDT_2023
Cuda compilation tools, release 12.2, V12.2.140
Build cuda_12.2.r12.2/compiler.33191640_0
/bin/bash: line 1: nvidia-smi: command not found


In [ ]:
!nvidia-smi #zmienione w runtime type na t4 gpu

Mon Jul  1 19:57:51 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   66C    P8              11W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import torch
print(torch.__version__)


2.3.0+cu121


## Introduction to tensors
Creating tensors

PyTorch tensor are created using 'troch.Tensor()' -= https://pytorch.org/docs/stable/tensors.html

In [ ]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Get tensor back as Python int
scalar.item()

7

In [ ]:
#Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                        [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])

TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
TENSOR2= torch.tensor([[[1],[2],[3],[4],[5],[6]]])

TENSOR2

tensor([[[1],
         [2],
         [3],
         [4],
         [5],
         [6]]])

In [ ]:
TENSOR2.ndim

3

In [ ]:
TENSOR2.shape

torch.Size([1, 6, 1])

In [ ]:
TENSOR3= torch.tensor([[[1],[2]],[[3],[4]],[[5],[6]]])

TENSOR3

tensor([[[1],
         [2]],

        [[3],
         [4]],

        [[5],
         [6]]])

In [ ]:
TENSOR3.ndim

3

In [ ]:
TENSOR3.shape

torch.Size([3, 2, 1])

### RANDOM TENSORS

Random tensor are imprtant because the way many neural netowrks learn is that they start with tensors full of random numbers and then adjuct thise random numbers to better represent the data

Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers

torch.rand = https://pytorch.org/docs/stable/generated/torch.rand.html

In [ ]:
#Random tensors
#Create random tensor of shape/shape (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.2745, 0.4793, 0.9973, 0.6225],
        [0.8652, 0.1665, 0.9228, 0.1242],
        [0.6973, 0.5892, 0.3153, 0.4121]])

In [ ]:
#Create a random tensor with similar shape to an image
random_image_size_tensor = torch.rand(size=(224,224,3)) #height,width,colour channels (R,G,B)
random_image_size_tensor

tensor([[[0.0241, 0.7350, 0.8997],
         [0.8852, 0.7360, 0.4169],
         [0.6262, 0.0778, 0.8226],
         ...,
         [0.6019, 0.3599, 0.5590],
         [0.6841, 0.0796, 0.1399],
         [0.3175, 0.8301, 0.8749]],

        [[0.2790, 0.1734, 0.0384],
         [0.0655, 0.7959, 0.6559],
         [0.7028, 0.7671, 0.8235],
         ...,
         [0.7986, 0.6062, 0.2393],
         [0.2707, 0.4032, 0.6545],
         [0.0534, 0.8110, 0.6434]],

        [[0.2604, 0.0465, 0.4335],
         [0.5778, 0.6353, 0.3369],
         [0.0908, 0.2138, 0.1683],
         ...,
         [0.2226, 0.3799, 0.5368],
         [0.3197, 0.5632, 0.5155],
         [0.7979, 0.5702, 0.3484]],

        ...,

        [[0.2828, 0.2514, 0.2314],
         [0.7709, 0.8374, 0.8630],
         [0.3331, 0.7585, 0.7807],
         ...,
         [0.6613, 0.6435, 0.6397],
         [0.3376, 0.4185, 0.8338],
         [0.5712, 0.4700, 0.8880]],

        [[0.3402, 0.2595, 0.0960],
         [0.5096, 0.9947, 0.4674],
         [0.