<a href="https://colab.research.google.com/github/patero22/PyTorch_Course/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00 PyTorch Fundamentals
resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

Questions on github/discussions

In [3]:
print("Pytorch")

Pytorch


In [4]:
!/usr/local/cuda/bin/nvcc --version


nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Tue_Aug_15_22:02:13_PDT_2023
Cuda compilation tools, release 12.2, V12.2.140
Build cuda_12.2.r12.2/compiler.33191640_0


In [5]:
!nvidia-smi #zmienione w runtime type na t4 gpu

/bin/bash: line 1: nvidia-smi: command not found


In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import torch
print(torch.__version__)


2.3.0+cu121


## Introduction to tensors
Creating tensors

PyTorch tensor are created using 'troch.Tensor()' -= https://pytorch.org/docs/stable/tensors.html

In [7]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [8]:
scalar.ndim

0

In [9]:
# Get tensor back as Python int
scalar.item()

7

In [10]:
#Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [11]:
vector.ndim

1

In [12]:
vector.shape

torch.Size([2])

In [13]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                        [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [14]:
MATRIX.ndim

2

In [15]:
MATRIX.shape

torch.Size([2, 2])

In [16]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                        [4,5,6],
                        [7,8,9]]])

TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [17]:
TENSOR.ndim

3

In [18]:
TENSOR.shape

torch.Size([1, 3, 3])

In [19]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [20]:
TENSOR2= torch.tensor([[[1],[2],[3],[4],[5],[6]]])

TENSOR2

tensor([[[1],
         [2],
         [3],
         [4],
         [5],
         [6]]])

In [21]:
TENSOR2.ndim

3

In [22]:
TENSOR2.shape

torch.Size([1, 6, 1])

In [23]:
TENSOR3= torch.tensor([[[1],[2]],[[3],[4]],[[5],[6]]])

TENSOR3

tensor([[[1],
         [2]],

        [[3],
         [4]],

        [[5],
         [6]]])

In [24]:
TENSOR3.ndim

3

In [25]:
TENSOR3.shape

torch.Size([3, 2, 1])

### RANDOM TENSORS

Random tensor are imprtant because the way many neural netowrks learn is that they start with tensors full of random numbers and then adjuct thise random numbers to better represent the data

Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers

torch.rand = https://pytorch.org/docs/stable/generated/torch.rand.html

In [26]:
#Random tensors
#Create random tensor of shape/shape (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.4806, 0.1373, 0.7055, 0.4266],
        [0.0925, 0.0427, 0.8153, 0.2280],
        [0.0431, 0.0848, 0.0807, 0.8902]])

In [27]:
#Create a random tensor with similar shape to an image
random_image_size_tensor = torch.rand(size=(224,224,3)) #height,width,colour channels (R,G,B)
random_image_size_tensor

tensor([[[0.8425, 0.6103, 0.1470],
         [0.8219, 0.9271, 0.0303],
         [0.3914, 0.3230, 0.0796],
         ...,
         [0.2603, 0.4409, 0.6505],
         [0.6842, 0.0301, 0.6679],
         [0.2123, 0.2658, 0.3377]],

        [[0.7156, 0.5319, 0.5325],
         [0.4441, 0.6428, 0.7606],
         [0.1511, 0.8403, 0.7579],
         ...,
         [0.6228, 0.5985, 0.3657],
         [0.2019, 0.1137, 0.5703],
         [0.0857, 0.2238, 0.5607]],

        [[0.1505, 0.3763, 0.3318],
         [0.7377, 0.1729, 0.3316],
         [0.6010, 0.1379, 0.1145],
         ...,
         [0.8620, 0.2276, 0.6991],
         [0.0631, 0.7611, 0.1844],
         [0.0891, 0.0744, 0.8734]],

        ...,

        [[0.6355, 0.8173, 0.6402],
         [0.7541, 0.6181, 0.0743],
         [0.2829, 0.3923, 0.2468],
         ...,
         [0.5314, 0.4305, 0.4527],
         [0.7767, 0.1120, 0.2770],
         [0.2171, 0.9312, 0.3755]],

        [[0.4058, 0.2829, 0.2311],
         [0.9895, 0.9030, 0.8809],
         [0.

### Zeros and ones

In [28]:
# Create a tensor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [29]:
# tensor of all ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [30]:
ones.dtype

torch.float32

### Create a range of tensors and tensors-like

In [35]:
# use torch.arange()

one_to_ten = torch.arange(start=0,end=1000, step=77)
one_to_ten

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [36]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [39]:
#Float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False) #track gradiens with this tensor operations
float_32_tensor

tensor([3., 6., 9.])

In [38]:
float_32_tensor.dtype

torch.float32

In [41]:
float_16_tensor = float_32_tensor.type(torch.half) #torch.half = torch.float16
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [42]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [43]:
int_32_tensor = torch.tensor([3,6,9],dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [45]:
float_32_tensor*int_32_tensor

tensor([ 9., 36., 81.])

### Getting infromation from tensors

tensor.dtype
tensor.shape
tensor.device

In [47]:
#some tensor
some_tensor = torch.rand(3,4)

In [48]:
print(some_tensor)

tensor([[0.0220, 0.1181, 0.1667, 0.6485],
        [0.5213, 0.6013, 0.2328, 0.2983],
        [0.7308, 0.0950, 0.9070, 0.6362]])


In [49]:
print(some_tensor.dtype)

torch.float32


In [50]:
print(some_tensor.shape)

torch.Size([3, 4])


In [51]:
print(some_tensor.device)

cpu


### Manipulating tensor (tensor operations)

operations include:
* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix multplication

In [54]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [55]:
tensor * 10

tensor([10, 20, 30])

In [56]:
#Try out PyTorch inbuilt fucntions
torch.mul(tensor,10)

tensor([10, 20, 30])